{"name": "Test login with incorrect credentials", "status": "passed", "start": 1730745762621, "stop": 1730745762820, "uuid": "01bf3a64-6d8c-4f42-99fb-9827a4d0ff3f", "historyId": "44fe22fe56e2314a6384b813c325a038", "testCaseId": "44fe22fe56e2314a6384b813c325a038", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_incorrect_credentials", "labels": [{"name": "suite", "value": "User Login Tests"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DRAKOSH"}, {"name": "thread", "value": "16600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}